export const CHARACTER_BIOS: Record<string, string> = {
    "Carrow Meltwright": "The only leader in the province who can balance a full trade ledger on a single stick of pulled toffee. He believes a wide smile is the best currency and a sticky handshake is a sign of true trust.",
    "Mirelle Glazebell": "Legend says she can hear a single air bubble in a batch of cream from three blocks away. She carries a silver whisk as her scepter and a jar of 'Emergency Glaze' at all times.",
    "Beni Banana": "A master of the 'Peel-and-Reveal' strategy, he has guided the valley through seven banana-harvest moon gluts without a single bruised fruit.",
    "Mirek Glossbark": "He carries a personal 'Shine-Meter' to ensure the grove's exports meet the 'Mirror-Finish' standard. He believes true shine comes from a happy soul.",
    "Yara Frostmint": "Her icy stare is said to be the only thing colder than the peak's midnight oil reserves. Yet, she knows that even the deepest ice can be melted by a warm heart.",
    "Rurik Emberwhisk": "He uses a specialized obsidian whisk to handle the lake's most temperamental geothermal vents. He believes a bubbling joke is better than a steaming decree any day.",
    "Dagna Riftcocoa": "She can tell the depth of a canyon rift just by the pitch of an echo bouncing off the cocoa walls.",
    "Nilo Veinwarden": "The only warden who can navigate the deepest cream-lanes without a lantern; he 'feels' the texture of the air.",
    "Parnell Waycrumb": "He keeps the crossroads clock timed to the exact second a fresh batch of brownies reaches peak density. He says a warm brownie is just a hug with a crust.",
    "Brann Hazelward": "His personal nut-roaster is calibrated to the exact temperature of a summer sunrise. He treats every hazelnut like a tiny, edible planet and every harvest like a grand cosmic event.",
    "Rilla Driftjar": "She once navigated an oversized peanut-butter raft over the falls using only a giant serving spoon and a very catchy sea-shanty.",
    "Sera Amberlift": "She personally vibrates every amber lift cable to ensure it's as resilient as a fresh honey slab. She believes sweet synergy is the best kind of gravity.",
    "Oren Linkforge": "Known for his 'Sticky Stamp' technique; no manifest goes unsigned for more than a single second. He swears by the motto: 'A quick pun is the best shortcut'.",
    "Vico Prismshore": "He holds the province record for identifying 142 distinct sub-shades of 'Neon Raspberry' sprinkles. He believes colors are just moods you can eat.",
    "Elio Docksyrup": "Master of the 'Slow Pour', he can fill a cargo ship with syrup without creating a single air pocket.",
    "Selene Tideswirl": "A champion surfer who can draft a trade agreement while riding a triple-shot caramel wave.",
    "Corin Nutquay": "He once balanced a ten-ton nut-load on a single crane-hook just to settle a bet. He says a happy quay leads to a sweet day.",
};

export const TOWN_CAST: Record<string, { head: string; carpenter: string; painter: string; scientist: string }> = {
    'toffee-town': { head: 'Carrow Meltwright', carpenter: 'Pella', painter: 'Bo', scientist: 'Rumi' },
    'peppermint-peak': { head: 'Yara Frostmint', carpenter: 'Flint', painter: 'Snow', scientist: 'Mist' },
    'eclair-square': { head: 'Mirelle Glazebell', carpenter: 'Flo', painter: 'Kip', scientist: 'Zara' },
    'creme-tunnels': { head: 'Nilo Veinwarden', carpenter: 'Veil', painter: 'Glow', scientist: 'Nim' },
    'banoffee-valley': { head: 'Beni Banana', carpenter: 'Peel', painter: 'Gold', scientist: 'Zip' },
    'ganache-grove': { head: 'Mirek Glossbark', carpenter: 'Bark', painter: 'Shade', scientist: 'Leaf' },
    'cocoa-canyon': { head: 'Dagna Riftcocoa', carpenter: 'Echo', painter: 'Clay', scientist: 'Drift' },
    'lava-cake-lake': { head: 'Rurik Emberwhisk', carpenter: 'Ash', painter: 'Flame', scientist: 'Steam' },
    'brownie-crossroads': { head: 'Parnell Waycrumb', carpenter: 'Rust', painter: 'Sienna', scientist: 'Chip' },
    'hazelnut-terrace': { head: 'Brann Hazelward', carpenter: 'Nix', painter: 'Wren', scientist: 'Opal' },
    'peanut-butter-falls': { head: 'Rilla Driftjar', carpenter: 'Finn', painter: 'Ivy', scientist: 'Dash' },
    'honeycomb-heights': { head: 'Sera Amberlift', carpenter: 'Buzz', painter: 'Cleo', scientist: 'Hex' },
    'nougat-node': { head: 'Oren Linkforge', carpenter: 'Bolt', painter: 'Kit', scientist: 'Flux' },
    'sprinkle-sands': { head: 'Vico Prismshore', carpenter: 'Coral', painter: 'Ray', scientist: 'Gem' },
    'butterscotch-bay': { head: 'Elio Docksyrup', carpenter: 'Tide', painter: 'Lumi', scientist: 'Pip' },
    'praline-port': { head: 'Corin Nutquay', carpenter: 'Mast', painter: 'Quill', scientist: 'Brine' },
    'caramel-cove': { head: 'Selene Tideswirl', carpenter: 'Surf', painter: 'Reef', scientist: 'Foam' },
};

export const TOWN_LEGENDS: Record<string, string> = {
    'toffee-town': 'Long before the Chocolate Era, the Great Toffee Stream ran molten gold through the capital. Legend says the first Town Head pulled a toffee strand that bent time itself.',
    'peppermint-peak': 'The White-Chocolate Spruce at the summit is rumored to be the coldest object in the province—so cold it preserves the memories of anyone who touches it.',
    'eclair-square': 'The Grand Eclair Architect once sculpted a pastry so perfect that it sang at dawn. Every glaze parade since echoes that single, magical note.',
    'creme-tunnels': 'The Velvety Cream Vine first grew from a single drop of dream-milk, and its glow has never dimmed.',
    'banoffee-valley': 'Banoffee Valley was born when a baker tossed a bowl of caramel into a banana cyclone. The resulting landscape is a tribute to accidental greatness.',
    'ganache-grove': 'The Glossy Emerald-Cacao trees only produce ganache under starlight. The forest itself is alive, and the grove hums a lullaby each midnight.',
    'cocoa-canyon': 'The Deep-Vein Mocha Birch roots run so deep they touch the very bottom of Candybrook.',
    'lava-cake-lake': 'The Molten Core was once a sleeping chocolate dragon. Its warmth still heats every spring in the basin.',
    'brownie-crossroads': 'Every brownie baked at the Junction carries a crumb from the Original Crossroad Stone—a meteorite made entirely of dark chocolate.',
    'hazelnut-terrace': 'The Golden Praline Oak at the summit is said to crack open its own nuts during harvest moon, showering the terraces with roasted blessings.',
    'peanut-butter-falls': 'Beneath the cascading peanut streams lies a hidden grotto where ancient rafters carved the first river maps of Candybrook in crunchy stone.',
    'honeycomb-heights': 'The Amber Lift was not built—it grew. A single honeybee, colossal and wise, carved the first vertical shaft with her own wings.',
    'nougat-node': 'At the exact center of every crossroad stands an invisible Chewy Pillar. Those who pause there long enough can hear the entire province breathing.',
    'sprinkle-sands': 'The Rainbow Shore was born when a storm of pure joy scattered seven colors across the coast. They say each sprinkle still holds a tiny wish.',
    'butterscotch-bay': 'The six-hour sunset is no natural wonder; it is the lingering gaze of a syrup goddess who fell in love with the bay centuries ago.',
    'praline-port': 'The first harbor bells were carved from fossilized praline and tuned to calm storm tides. Sailors still swear the quay can sing ships safely home.',
    'caramel-cove': 'The Syrup-Salt Willow at the shore weeps caramel tears at sunset. Collecting even one drop is said to bring a year of sweet fortune.',
};
